#!/bin/sh
#
# @name scale_tiltwing
#
# @type Quadrotor Wide
#
# @maintainer Sled Aero
#

. ${R}etc/init.d/rc.mc_defaults
param set-default CA_AIRFRAME 0
param set-default CA_ROTOR_COUNT 4
param set-default CA_ROTOR0_PX 0.18406724125015453
param set-default CA_ROTOR0_PY 0.2070000006778513
param set-default CA_ROTOR0_PZ 0.059496613560949985
param set-default CA_ROTOR0_KM 0.05
param set-default CA_ROTOR1_PX -0.28393275833506965
param set-default CA_ROTOR1_PY -0.20699999976593547
param set-default CA_ROTOR1_PZ 0.055496610964107934
param set-default CA_ROTOR1_KM 0.05
param set-default CA_ROTOR2_PX 0.18406724165667115
param set-default CA_ROTOR2_PY -0.20699999932214863
param set-default CA_ROTOR2_PZ 0.05949661193044009
param set-default CA_ROTOR2_KM -0.05
param set-default CA_ROTOR3_PX -0.28393275874158624
param set-default CA_ROTOR3_PY 0.20700000023406456
param set-default CA_ROTOR3_PZ 0.05549661259461777
param set-default CA_ROTOR3_KM -0.05
param set-default PWM_MAIN_FUNC1 101
param set-default PWM_MAIN_FUNC2 102
param set-default PWM_MAIN_FUNC3 103
param set-default PWM_MAIN_FUNC4 104
param set-default MC_ROLLRATE_P 0.15
param set-default MC_ROLLRATE_I 0.2
param set-default MC_ROLLRATE_D 0.003
param set-default MC_PITCHRATE_P 0.15
param set-default MC_PITCHRATE_I 0.2
param set-default MC_PITCHRATE_D 0.003
param set-default MC_YAWRATE_P 0.15
param set-default MC_YAWRATE_I 0.1
param set-default MC_YAWRATE_D 0.0